// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBpL0I6KY0fE9o35COypz8XAuOqDC7Rc0',
    appId: '1:834418935197:web:fdf18d9ea89ffc8fd0db74',
    messagingSenderId: '834418935197',
    projectId: 'orden-325a5',
    authDomain: 'orden-325a5.firebaseapp.com',
    storageBucket: 'orden-325a5.firebasestorage.app',
    measurementId: 'G-CC8DMNWZ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiI6oko7E-cdyn0OxP4qokzupR0mH69M',
    appId: '1:834418935197:android:414aa392c0da0954d0db74',
    messagingSenderId: '834418935197',
    projectId: 'orden-325a5',
    storageBucket: 'orden-325a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSdF1NmaQ29Q9ajd-NX2dWGnOxsATYRc8',
    appId: '1:834418935197:ios:709f55c67d7ca340d0db74',
    messagingSenderId: '834418935197',
    projectId: 'orden-325a5',
    storageBucket: 'orden-325a5.firebasestorage.app',
    iosClientId: '834418935197-3lcphrg6b0gom701uhlih48oeed9s1rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.orden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSdF1NmaQ29Q9ajd-NX2dWGnOxsATYRc8',
    appId: '1:834418935197:ios:709f55c67d7ca340d0db74',
    messagingSenderId: '834418935197',
    projectId: 'orden-325a5',
    storageBucket: 'orden-325a5.firebasestorage.app',
    iosClientId: '834418935197-3lcphrg6b0gom701uhlih48oeed9s1rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.orden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBpL0I6KY0fE9o35COypz8XAuOqDC7Rc0',
    appId: '1:834418935197:web:291caf152c7bd7edd0db74',
    messagingSenderId: '834418935197',
    projectId: 'orden-325a5',
    authDomain: 'orden-325a5.firebaseapp.com',
    storageBucket: 'orden-325a5.firebasestorage.app',
    measurementId: 'G-T5B4GZX0QG',
  );
}
