// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlCbjvE6akMqBM-obEol9txNPo9xzxjU',
    appId: '1:756698851622:web:7ce65f40592d52c25379e7',
    messagingSenderId: '756698851622',
    projectId: 'ordensoftii',
    authDomain: 'ordensoftii.firebaseapp.com',
    storageBucket: 'ordensoftii.firebasestorage.app',
    measurementId: 'G-CRSNRVE3VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNN-qG0IdDw0r8FKgXTW3RUojGPhNQlCs',
    appId: '1:756698851622:android:6ef5173ac83a73b55379e7',
    messagingSenderId: '756698851622',
    projectId: 'ordensoftii',
    storageBucket: 'ordensoftii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVc9O8VmqiGYFVopOzlyjVpcZlwqVXYw',
    appId: '1:756698851622:ios:853427c98ca0aee15379e7',
    messagingSenderId: '756698851622',
    projectId: 'ordensoftii',
    storageBucket: 'ordensoftii.firebasestorage.app',
    iosBundleId: 'com.example.orden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVc9O8VmqiGYFVopOzlyjVpcZlwqVXYw',
    appId: '1:756698851622:ios:853427c98ca0aee15379e7',
    messagingSenderId: '756698851622',
    projectId: 'ordensoftii',
    storageBucket: 'ordensoftii.firebasestorage.app',
    iosBundleId: 'com.example.orden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqlCbjvE6akMqBM-obEol9txNPo9xzxjU',
    appId: '1:756698851622:web:3564ad96c2a4d4355379e7',
    messagingSenderId: '756698851622',
    projectId: 'ordensoftii',
    authDomain: 'ordensoftii.firebaseapp.com',
    storageBucket: 'ordensoftii.firebasestorage.app',
    measurementId: 'G-E3TV31KRPZ',
  );
}
